
### getting Header details

# GET  http://localhost:4004/odata/v4/nauticalservice/xNAUTIxVOYAGEHEADERTOITEM/1000000034?$expand=tocostcharge,toitem
GET  http://localhost:4004/odata/v4/nauticalservice/xNAUTIxVOYAGEHEADERTOITEM/1000000034?$expand=tobiditem

### getting

###hkjh

GET  http://localhost:4004/odata/v4/nauticalservice/voyapprovalSet(Vreqno='2000000187',Voyno='1000000156',Zlevel='02',Uname='PANKAJ.J')

### Put for voyage approval
PUT  http://localhost:4004/odata/v4/nauticalservice/voyapprovalSet(Vreqno='2000000187',Voyno='1000000156',Zlevel='02',Uname='PANKAJ.J')
Content-Type: application/json

{
     
      "Zcomm": "test appr",
      "Zaction": "APPR"
    }
   
###vhd
POST http://localhost:4004/odata/v4/nauticalservice/voyapprovalSet
Content-Type: application/json

{
  "Vreqno":"",
  "Zemail":"sarath.venkateswara@ingenxtec.com",
  "Voyno": "1000000147"
}

### POST REQUEST FOR VOYAGE TYPE WITH iTEM AND COST DETAILS
POST http://localhost:4004/odata/v4/nauticalservice/xNAUTIxVOYAGEHEADERTOITEM
Content-Type: application/json

{
  "Bidtype": "SB",
  "Carty": "1000",
  "Chpno": "",
  "Chtyp": "",
  "Curr": "INR",
  "Currkeys": "",
  "Docind": "",
  "Frcost": 60000,
  "Frcost_Act": 0,
  "Freght": 150000,
  "Frtco": 0,
  "Frtu": "L/S",
  "Frtu_Act": "",
  "GV_CSTATUS": "Voyage Created",
  "Party": "",
  "Ref_Voyno": "",
  "Refdoc": "",
  "Vessn": "",
  "Vimo": "",
  "Vnomtk": "",
  "Voynm": "Test Voyage 9/11",
  "Voyno": "1000000034",
  "Voyty": "1000",
  "Vstat": "",
  "toitem": [
    {
      "Voyno": "1000000034",
      "Vlegn": 1,
      "Portc": "INBOM",
      "Portn": "MUMBAI",
      "Pdist": 0,
      "Medst": "NM",
      "Vspeed": 9.5,
      "Ppdays": 3,
      "Vsdays": 0,
      "Vetad": "2023-09-07",
      "Vetat": "00:00:00",
      "Vetdd": "2023-09-10",
      "Vetdt": "00:00:00",
      "Vwead": "1",
      "Pstat": "",
      "Matnr": "",
      "Maktx": "",
      "Cargs": 10000,
      "Cargu": "TO",
      "Othco": 10000,
      "Frcost": 0,
      "Totco": 10000
    },
    {
      "Voyno": "1000000034",
      "Vlegn": 2,
      "Portc": "INVTZ",
      "Portn": "VISAKHAPATNAM",
      "Pdist": 1768,
      "Medst": "NM",
      "Vspeed": 9.5,
      "Ppdays": 2,
      "Vsdays": 7.909,
      "Vetad": "2023-09-17",
      "Vetat": "21:48:00",
      "Vetdd": "2023-09-19",
      "Vetdt": "21:48:00",
      "Vwead": "2",
      "Pstat": "",
      "Matnr": "",
      "Maktx": "",
      "Cargs": 8000,
      "Cargu": "TO",
      "Othco": 5000,
      "Frcost": 48000,
      "Totco": 53000
    },
    {
      "Voyno": "1000000034",
      "Vlegn": 3,
      "Portc": "INPRT",
      "Portn": "PARADIP",
      "Pdist": 270,
      "Medst": "NM",
      "Vspeed": 9.5,
      "Ppdays": 1,
      "Vsdays": 1.22,
      "Vetad": "2023-09-21",
      "Vetat": "03:04:00",
      "Vetdd": "2023-09-22",
      "Vetdt": "03:04:00",
      "Vwead": "3",
      "Pstat": "",
      "Matnr": "",
      "Maktx": "",
      "Cargs": 2000,
      "Cargu": "TO",
      "Othco": 2500,
      "Frcost": 12000,
      "Totco": 17500
    }
  ],
  "tocostcharge": [
    {
      "Voyno": "1000000034",
      "Vlegn": 1,
      "Costcode": "1001",
      "Costu": "L/S",
      "Prcunit": "",
      "Procost": 10000,
      "Costcurr": "INR",
      "Cstcodes": "PORT CHARGES",
      "CostCheck": false
    },
    {
      "Voyno": "1000000034",
      "Vlegn": 2,
      "Costcode": "1001",
      "Costu": "L/S",
      "Prcunit": "",
      "Procost": 5000,
      "Costcurr": "INR",
      "Cstcodes": "PORT CHARGES",
      "CostCheck": false
    },
    {
      "Voyno": "1000000034",
      "Vlegn": 3,
      "Costcode": "1001",
      "Costu": "L/S",
      "Prcunit": "",
      "Procost": 2500,
      "Costcurr": "INR",
      "Cstcodes": "PORT CHARGES",
      "CostCheck": false
    }
  ],
  "tobiditem": [
    {
      "CodeDesc": "DEMMURAGE",
      "Cunit": "",
      "Cvalue": "",
      "Good": "",
      "Mand": "",
      "Must": "",
      "RevBid": false,
      "Value": "",
      "Voyno": "1000000034",
      "Zcode": "DEMMURAGE",
      "Zmax": "",
      "Zmin": ""
    },
    {
      "CodeDesc": "FREIGHT",
      "Cunit": "",
      "Cvalue": "",
      "Good": "",
      "Mand": "",
      "Must": "",
      "RevBid": false,
      "Value": "",
      "Voyno": "1000000034",
      "Zcode": "FREIG",
      "Zmax": "",
      "Zmin": ""
    }
  ]
}

# {
#   "Voyno": "1000000034",
#   "Voynm": "Test Voyage 9/11",
#   "Vnomtk": "",
#   "Refdoc": "",
#   "Docind": "",
#   "Vessn": "",
#   "Vimo": "",
#   "Chtyp": "",
#   "Chpno": "",
#   "Currkeys": "",
#   "Frtco": "0",
#   "Vstat": "",
#   "Voyty": "1000",
#   "Carty": "1000",
#   "Curr": "INR",
#   "Freght": "150000",
#   "Party": "",
#   "Bidtype": "SB",
#   "Frcost": "60000",
#   "Frtu": "L/S",
#   "Frcost_Act": "0",
#   "Frtu_Act": "",
#   "Ref_Voyno": "",
#   "GV_CSTATUS": "Voyage Created",
#   "toitem": [
#     {
#       "Voyno": "1000000034",
#       "Vlegn": 1,
#       "Portc": "INBOM",
#       "Portn": "MUMBAI",
#       "Pdist": "0",
#       "Medst": "NM",
#       "Vspeed": "9.5",
#       "Ppdays": "3",
#       "Vsdays": "0",
#       "Vetad": "2023-09-07",
#       "Vetat": "00:00:00",
#       "Vetdd": "2023-09-10",
#       "Vetdt": "00:00:00",
#       "Vwead": "1",
#       "Pstat": "",
#       "Matnr": "",
#       "Maktx": "",
#       "Cargs": "10000",
#       "Cargu": "TO",
#       "Othco": "10000",
#       "Frcost": "0",
#       "Totco": "10000"
#     },
#     {
#       "Voyno": "1000000034",
#       "Vlegn": 2,
#       "Portc": "INVTZ",
#       "Portn": "VISAKHAPATNAM",
#       "Pdist": 1768,
#       "Medst": "NM",
#       "Vspeed": 9.5,
#       "Ppdays": 2,
#       "Vsdays": 7.909,
#       "Vetad": "2023-09-17",
#       "Vetat": "21:48:00",
#       "Vetdd": "2023-09-19",
#       "Vetdt": "21:48:00",
#       "Vwead": "2",
#       "Pstat": "",
#       "Matnr": "",
#       "Maktx": "",
#       "Cargs": 8000,
#       "Cargu": "TO",
#       "Othco": 5000,
#       "Frcost": 48000,
#       "Totco": 53000
#     },
#     {
#       "Voyno": "1000000034",
#       "Vlegn": 3,
#       "Portc": "INPRT",
#       "Portn": "PARADIP",
#       "Pdist": 270,
#       "Medst": "NM",
#       "Vspeed": 9.5,
#       "Ppdays": 1,
#       "Vsdays": 1.22,
#       "Vetad": "2023-09-21",
#       "Vetat": "03:04:00",
#       "Vetdd": "2023-09-22",
#       "Vetdt": "03:04:00",
#       "Vwead": "3",
#       "Pstat": "",
#       "Matnr": "",
#       "Maktx": "",
#       "Cargs": 2000,
#       "Cargu": "TO",
#       "Othco": 2500,
#       "Frcost": 12000,
#       "Totco": 17500
#     }
#   ],
#   "tocostcharge": [
#     {
#       "Voyno": "1000000034",
#       "Vlegn": 1,
#       "Costcode": "1001",
#       "Costu": "L/S",
#       "Prcunit": "",
#       "Procost": "10000",
#       "Costcurr": "INR",
#       "Cstcodes": "PORT CHARGES",
#       "CostCheck": false
#     },
#     {
#       "Voyno": "1000000034",
#       "Vlegn": 2,
#       "Costcode": "1001",
#       "Costu": "L/S",
#       "Prcunit": "",
#       "Procost": "5000",
#       "Costcurr": "INR",
#       "Cstcodes": "PORT CHARGES",
#       "CostCheck": false
#     },
#     {
#       "Voyno": "1000000034",
#       "Vlegn": 3,
#       "Costcode": "1001",
#       "Costu": "L/S",
#       "Prcunit": "",
#       "Procost": "2500",
#       "Costcurr": "INR",
#       "Cstcodes": "PORT CHARGES",
#       "CostCheck": false
#     }
#   ],
#   "tobiditem":[
#     {
#         "Voyno": "1000000034",
#         "Zcode": "CLASS",
#         "Value": "A",
#         "Cvalue": "0",
#         "Cunit": "",
#         "CodeDesc": "CLASS OF VESSEL",
#         "RevBid": true,
#         "Good": "X",
#         "Mand": "",
#         "Must": "",
#         "Zmin": "4",
#         "Zmax": "5"
#     },
#     {
#         "Voyno": "1000000034",
#         "Zcode": "CLASS",
#         "Value": "B",
#         "Cvalue": "0.000",
#         "Cunit": "",
#         "CodeDesc": "CLASS OF VESSEL",
#         "RevBid": true,
#         "Good": "X",
#         "Mand": "",
#         "Must": "",
#         "Zmin": "2",
#         "Zmax": "3"
#     },
#     {
#         "Voyno": "1000000034",
#         "Zcode": "PORT",
#         "Value": "INBOM",
#         "Cvalue": "0.000",
#         "Cunit": "",
#         "CodeDesc": "LAST PORT OF CALL",
#         "RevBid": true,
#         "Good": "X",
#         "Mand": "",
#         "Must": "",
#         "Zmin": "0",
#         "Zmax": "5"
#     },
#     {
#         "Voyno": "1000000034",
#         "Zcode": "COOR",
#         "Value": "IN",
#         "Cvalue": "0.000",
#         "Cunit": "",
#         "CodeDesc": "COUNTRY OF ORIGIN",
#         "RevBid": true,
#         "Good": "X",
#         "Mand": "",
#         "Must": "",
#         "Zmin": "0",
#         "Zmax": "5"
#     },
#     {
#         "Voyno": "1000000034",
#         "Zcode": "DAT1",
#         "Value": "20.09.2023",
#         "Cvalue": "0",
#         "Cunit": "",
#         "CodeDesc": "LAST CLEANING DATE",
#         "RevBid": true,
#         "Good": "X",
#         "Mand": "",
#         "Must": "",
#         "Zmin": "3",
#         "Zmax": "5"
#     },
#     {
#         "Voyno": "1000000034",
#         "Zcode": "PORT",
#         "Value": "INBOM",
#         "Cvalue": "0",
#         "Cunit": "",
#         "CodeDesc": "LAST PORT OF CALL",
#         "RevBid": true,
#         "Good": "X",
#         "Mand": "",
#         "Must": "",
#         "Zmin": "3",
#         "Zmax": "5"
#     }
# ] 
# }

### submit quoataion
POST http://localhost:4004/odata/v4/nauticalservice/xNAUTIxSUBMITQUATATIONPOST
Content-Type: application/json

{
  "Biddate": "2024-05-29",
  "Bidtime": "10:17:51",
  "Chrnmin": "4000000020",
  "Lifnr": "2100000002",
  "Vimono": "imee2",
  "Vname": "999877",
  "Voyno": "1000000152",
  "tovenditem": [
    {
      "Biddate": "2024-05-29",
      "Bidtime": "10:17:51",
      "Chrnmin": "4000000020",
      "CodeDesc": "COUNTRY OF ORIGIN",
      "Cunit": "",
      "Cvalue": "0.000",
      "Lifnr": "2100000002",
      "Value": "IN",
      "Voyno": "1000000152",
      "Zcode": "COOR",
      "Zcom": ""
    },
    {
      "Biddate": "2024-05-29",
      "Bidtime": "10:17:51",
      "Chrnmin": "4000000020",
      "CodeDesc": "LAST CLEANING DATE",
      "Cunit": "",
      "Cvalue": "0.000",
      "Lifnr": "2100000002",
      "Value": "2024-05-31",
      "Voyno": "1000000152",
      "Zcode": "DAT1",
      "Zcom": ""
    },
    {
      "Biddate": "2024-05-29",
      "Bidtime": "10:17:51",
      "Chrnmin": "4000000020",
      "CodeDesc": "LAST PORT OF CALL",
      "Cunit": "",
      "Cvalue": "0.000",
      "Lifnr": "2100000002",
      "Value": "INBOM",
      "Voyno": "1000000152",
      "Zcode": "PORT",
      "Zcom": ""
    },
    {
      "Biddate": "2024-05-29",
      "Bidtime": "10:17:51",
      "Chrnmin": "4000000020",
      "CodeDesc": "CLASS OF VESSEL",
      "Cunit": "",
      "Cvalue": "0.000",
      "Lifnr": "2100000002",
      "Value": "A",
      "Voyno": "1000000152",
      "Zcode": "CLASS",
      "Zcom": ""
    },
    {
      "Biddate": "2024-05-29",
      "Bidtime": "10:17:51",
      "Chrnmin": "4000000020",
      "CodeDesc": "DEMURRAGE",
      "Cunit": "INR",
      "Cvalue": "65656",
      "Lifnr": "2100000002",
      "Value": "",
      "Voyno": "1000000152",
      "Zcode": "DEMURRAGE",
      "Zcom": ""
    },
    {
      "Biddate": "2024-05-29",
      "Bidtime": "10:17:51",
      "Chrnmin": "4000000020",
      "CodeDesc": "FREIGHT",
      "Cunit": "INR",
      "Cvalue": "2000000",
      "Lifnr": "2100000002",
      "Value": "",
      "Voyno": "1000000152",
      "Zcode": "FREIG",
      "Zcom": ""
    }
  ]
}
### posting data
POST  http://localhost:4004/odata/v4/nauticalservice/ZCalculateSet
Content-Type: application/json

{
  "GvSpeed": "24",
  "ZCalcNav": [
    {
      "Medst": "NM",
      "Pdist": "00000",
      "Portc": "INBOM",
      "Portn": "MUMBAI",
      "Ppdays": "5",
      "Vetdd": "2024-04-05",
      "Vetdt": "17:48:45",
      "Vspeed": "24",
      "Vwead": "0"
    },
    {
      "Medst": "NM",
      "Pdist": "1971",
      "Portc": "INPRT",
      "Portn": "PARADIP",
      "Ppdays": "2",
      "Vspeed": "24",
      "Vwead": "0"
    }
  ]
}




 "toitem":[
                        {
                            "Cargs": "50000",
                            "Cargu": "TO",
                            "Frcost": "0",
                            "Maktx": "",
                            "Matnr": "",
                            "Medst": "NM",
                            "Othco": "0",
                            "Pdist": "0",
                            "Portc": "INBOM",
                            "Portn": "MUMBAI",
                            "Ppdays": "2",
                            "Pstat": "",
                            "Totco": "0",
                            "Vetad": "2024-05-06",
                            "Vetat": "06:40:03",
                            "Vetdd": "2024-05-08",
                            "Vetdt": "06:40:03",
                            "Vlegn": "1",
                            "Voyno": "1000000112",
                            "Vsdays": "0",
                            "Vspeed": "23",
                            "Vwead": "00"
                          },
                          {
                            "Cargs": "50000",
                            "Cargu": "TO",
                            "Frcost": "0",
                            "Maktx": "",
                            "Matnr": "",
                            "Medst": "NM",
                            "Othco": "0",
                            "Pdist": "1971",
                            "Portc": "INPRT",
                            "Portn": "PARADIP",
                            "Ppdays": "2",
                            "Pstat": "",
                            "Totco": "0",
                            "Vetad": "2024-05-11",
                            "Vetat": "21:22:03",
                            "Vetdd": "2024-05-13",
                            "Vetdt": "21:22:03",
                            "Vlegn": "2",
                            "Voyno": "1000000112",
                            "Vsdays": "3.571",
                            "Vspeed": "23",
                            "Vwead": "0"
                          }
                    ]

{


"Voyno": "1000000034",
  "Voynm": "Test Voyage 9/11",
  "Vnomtk": "",
  "Refdoc": "",
  "Docind": "",
  "Vessn": "",
  "Vimo": "",
  "Chtyp": "",
  "Chpno": "",
  "Currkeys": "",
  "Frtco": 0,
  "Vstat": "",
  "Voyty": "1000",
  "Carty": "1000",
  "Curr": "INR",
  "Freght": 150000,
  "Party": "",
  "Bidtype": "SB",
  "Frcost": 60000,
  "Frtu": "LSUM",
  "Frcost_Act": 0,
  "Frtu_Act": "",
  "Ref_Voyno": "",
  "GV_CSTATUS": "Voyage Created",
  "tocostcharge": [
    {
      "Voyno": "1000000034",
      "Vlegn": "0000000001",
      "Costcode": "1001",
      "Costu": "LSUM",
      "Prcunit": "",
      "Procost": 10000,
      "Costcurr": "INR",
      "Cstcodes": "PORT CHARGES",
      "CostCheck": false
    },
    {
      "Voyno": "1000000034",
      "Vlegn": "0000000002",
      "Costcode": "1001",
      "Costu": "LSUM",
      "Prcunit": "",
      "Procost": 5000,
      "Costcurr": "INR",
      "Cstcodes": "PORT CHARGES",
      "CostCheck": false
    },
    {
      "Voyno": "1000000034",
      "Vlegn": "0000000003",
      "Costcode": "1001",
      "Costu": "LSUM",
      "Prcunit": "",
      "Procost": 5000,
      "Costcurr": "INR",
      "Cstcodes": "PORT CHARGES",
      "CostCheck": false
    }
  ],
  "toitem": [
    {
      "Voyno": "1000000034",
      "Vlegn": "0000000001",
      "Portc": "INBOM",
      "Portn": "MUMBAI",
      "Pdist": 0,
      "Medst": "NM",
      "Vspeed": 9.5,
      "Ppdays": 3,
      "Vsdays": 0,
      "Vetad": "2023-09-07",
      "Vetat": "00:00:00",
      "Vetdd": "2023-09-10",
      "Vetdt": "00:00:00",
      "Vwead": "1",
      "Pstat": "",
      "Matnr": "",
      "Maktx": "",
      "Cargs": 10000,
      "Cargu": "TO",
      "Othco": 10000,
      "Frcost": 0,
      "Totco": 10000
    },
    {
      "Voyno": "1000000034",
      "Vlegn": "0000000002",
      "Portc": "INVTZ",
      "Portn": "VISAKHAPATNAM",
      "Pdist": 1768,
      "Medst": "NM",
      "Vspeed": 9.5,
      "Ppdays": 2,
      "Vsdays": 7.909,
      "Vetad": "2023-09-17",
      "Vetat": "21:48:00",
      "Vetdd": "2023-09-19",
      "Vetdt": "21:48:00",
      "Vwead": "2",
      "Pstat": "",
      "Matnr": "",
      "Maktx": "",
      "Cargs": 8000,
      "Cargu": "TO",
      "Othco": 5000,
      "Frcost": 48000,
      "Totco": 53000
    },
    {
      "Voyno": "1000000034",
      "Vlegn": "0000000003",
      "Portc": "INPRT",
      "Portn": "PARADIP",
      "Pdist": 270,
      "Medst": "NM",
      "Vspeed": 9.5,
      "Ppdays": 1,
      "Vsdays": 1.22,
      "Vetad": "2023-09-21",
      "Vetat": "03:04:00",
      "Vetdd": "2023-09-22",
      "Vetdt": "03:04:00",
      "Vwead": "3",
      "Pstat": "",
      "Matnr": "",
      "Maktx": "",
      "Cargs": 2000,
      "Cargu": "TO",
      "Othco": 5000,
      "Frcost": 12000,
      "Totco": 17000
    }
  ]
}

# {
#                     "Bidtype": "SB",
#                     "Carty": "1001",
#                     "Chpno": "",
#                     "Chtyp": "",
#                     "Curr": "INR",
#                     "Currkeys": "",
#                     "Docind": "",
#                     "Frcost": 0,
#                     "Frcost_Act": 0,
#                     "Freght": 0,
#                     "Frtco": "23450",
#                     "Frtu": "L/S",
#                     "Frtu_Act": "",
#                     "GV_CSTATUS": "Voyage Created",
#                     "Party": "",
#                     "Ref_Voyno": "",
#                     "Refdoc": "",
#                     "Vessn": "",
#                     "Vimo": "",
#                     "Vnomtk": "",
#                     "Voynm": "test07-05(3)",
#                     "Voyno": "1000000112",
#                     "Voyty": "1002",
#                     "Vstat": "",
#                     "toitem":[
#                         {
#                             "Cargs": "20000",
#                             "Cargu": "TO",
#                             "Frcost": "0",
#                             "Maktx": "",
#                             "Matnr": "",
#                             "Medst": "NM",
#                             "Othco": 0,
#                             "Pdist": 0,
#                             "Portc": "INBOM",
#                             "Portn": "MUMBAI",
#                             "Ppdays": 2,
#                             "Pstat": "",
#                             "Totco": 0,
#                             "Vetad": "2024-05-06",
#                             "Vetat": "06:40:03",
#                             "Vetdd": "2024-05-08",
#                             "Vetdt": "06:40:03",
#                             "Vlegn":  1        ,  
#                             "Voyno": "1000000112",
#                             "Vsdays": 0,
#                             "Vspeed": 23,
#                             "Vwead": "00"
#                           },
#                           {
#                             "Cargs": "20000",
#                             "Cargu": "TO",
#                             "Frcost": "23450",
#                             "Maktx": "",
#                             "Matnr": "",
#                             "Medst": "NM",
#                             "Othco": 0,
#                             "Pdist": 1971,
#                             "Portc": "INPRT",
#                             "Portn": "PARADIP",
#                             "Ppdays": 2,
#                             "Pstat": "",
#                             "Totco": 0,
#                             "Vetad": "2024-05-11",
#                             "Vetat": "21:22:03",
#                             "Vetdd": "2024-05-13",
#                             "Vetdt": "21:22:03",
#                             "Vlegn":  2,
#                             "Voyno": "1000000112",
#                             "Vsdays": "3.571",
#                             "Vspeed": 23,
#                             "Vwead": "0"
#                           }
#                     ]
                   
# }
###



# [
#     {
#       "Voyno": "1000000034",
#       "Zcode": "CLASS",
#       "Value": "A",
#       "Cvalue": "0.00",
#       "Cunit": "",
#       "CodeDesc": "CLASS OF VESSEL",
#       "RevBid": false,
#       "Good": "X",
#       "Mand": "",
#       "Must": "",
#       "Zmin": "3",
#       "Zmax": "4"
#     },
#     {
#       "Voyno": "1000000034",
#       "Zcode": "DAT1",
#       "Value": "01.09.2023",
#       "Cvalue": 0,
#       "Cunit": "",
#       "CodeDesc": "LAST CLEANING DATE",
#       "RevBid": false,
#       "Good": "X",
#       "Mand": "",
#       "Must": "",
#       "Zmin": 0,
#       "Zmax": 0
#     },
#     {
#       "Voyno": "1000000034",
#       "Zcode": "COOR",
#       "Value": "IN",
#       "Cvalue": 0,
#       "Cunit": "",
#       "CodeDesc": "COUNTRY OF ORIGIN",
#       "RevBid": false,
#       "Good": "X",
#       "Mand": "",
#       "Must": "",
#       "Zmin": 0,
#       "Zmax": 5
#     }
#   ]

GET http://localhost:4004/odata/v4/nauticalservice/getRoute?startLatitude=18.941&startLongitude=72.855&endLatitude=20.27769&endLongitude=86.69277